import type { Player } from "./types";

export const mockPlayers: Player[] = [
  {
    id: "1",
    name: "Aggressive Al",
    chips: 12_450,
    avatar: "",
    cards: [
      { rank: "A", suit: "spades" },
      { rank: "K", suit: "spades" },
    ],
    isDealer: false,
    isFolded: false,
    isActive: true,
  },
  {
    id: "2",
    name: "Cautious Cal",
    chips: 8_300,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
  },
  {
    id: "3",
    name: "Bluffing Betty",
    chips: 15_000,
    avatar: "",
    cards: null,
    isDealer: true,
    isFolded: false,
    isActive: false,
  },
  {
    id: "4",
    name: "Steady Steve",
    chips: 6_725,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: true,
    isActive: false,
  },
  {
    id: "5",
    name: "Wild Wanda",
    chips: 22_100,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
  },
  {
    id: "6",
    name: "Tight Tony",
    chips: 3_500,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
  },
  {
    id: "7",
    name: "Lucky Lucy",
    chips: 18_900,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
  },
  {
    id: "8",
    name: "Passive Pete",
    chips: 950,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: true,
    isActive: false,
  },
  {
    id: "9",
    name: "Risky Rick",
    chips: 41_000,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
  },
  {
    id: "10",
    name: "Calm Clara",
    chips: 10_075,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
  },
];
