import type { Card, Player, Pot } from "./types";

/** 3 flop cards dealt; turn and river not yet dealt. */
export const mockCommunityCards: Card[] = [
  { rank: "10", suit: "hearts" },
  { rank: "J", suit: "clubs" },
  { rank: "7", suit: "diamonds" },
];

export const mockPots: Pot[] = [
  { label: "Main Pot", amount: 9_500 },
  { label: "Side Pot", amount: 4_800 },
];

export const mockPlayers: Player[] = [
  {
    id: "1",
    name: "Aggressive Al",
    chips: 12_450,
    avatar: "",
    cards: [
      { rank: "A", suit: "spades" },
      { rank: "K", suit: "spades" },
    ],
    isDealer: false,
    isFolded: false,
    isActive: true,
    isAllIn: true,
    lastAction: "raise",
    currentBet: 12_450,
  },
  {
    id: "2",
    name: "Cautious Cal",
    chips: 8_300,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "call",
    currentBet: 400,
  },
  {
    id: "3",
    name: "Bluffing Betty",
    chips: 15_000,
    avatar: "",
    cards: null,
    isDealer: true,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "raise",
    currentBet: 800,
  },
  {
    id: "4",
    name: "Steady Steve",
    chips: 6_725,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "call",
    currentBet: 400,
  },
  {
    id: "5",
    name: "Wild Wanda",
    chips: 22_100,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "call",
    currentBet: 400,
  },
  {
    id: "6",
    name: "Tight Tony",
    chips: 3_500,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "call",
    currentBet: 400,
  },
  {
    id: "7",
    name: "Lucky Lucy",
    chips: 18_900,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "bet",
    currentBet: 400,
  },
  {
    id: "8",
    name: "Passive Pete",
    chips: 0,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: true,
    lastAction: "call",
    currentBet: 950,
  },
  {
    id: "9",
    name: "Risky Rick",
    chips: 41_000,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "call",
    currentBet: 400,
  },
  {
    id: "10",
    name: "Calm Clara",
    chips: 10_075,
    avatar: "",
    cards: null,
    isDealer: false,
    isFolded: false,
    isActive: false,
    isAllIn: false,
    lastAction: "raise",
    currentBet: 1200,
  },
];
